// src/App.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia';
import useMainStore from './stores/main';
import Card from './components/Card.vue';

const main = useMainStore();
const { repositories } = storeToRefs(main);
</script>

<template>
  <div class="bg-gray-800 h-screen w-screen font-sans">
    <div class="flex flex-col items-center">
      <div class="pt-6 pb-8">
        <a href="https://github.com/AstroCorp" target="_blank" class="bg-logo block h-20 w-20 rounded-full overflow-hidden p-2.5">
          <img src="/assets/logo.png" alt="logo" class="-mt-0.5" />
        </a>
      </div>
      
      <div class="text-center">
        <Card v-for="repo in repositories" :key="repo.title" :repository="repo" />
      </div>
    </div>
  </div>
</template>

// src/app/page.tsx
import Image from "next/image";

export default function Home() {
	return (
		<div className="flex flex-col h-screen items-center justify-center p-2">
			<div
				className="rounded-full overflow-hidden"
				style={{ 
					width: 150,
					height: 150,
					backgroundColor: "#2D394D",
				}}
			>
				<Image
					src="/Portfolio/logo.png"
					alt="Logo"
					width={150}
					height={150}
					className="-mt-1.5"
					priority
				/>
			</div>
			<p className="mt-4 text-white text-2xl">En mantenimiento...</p>
		</div>
	);
}
