// src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-footer',
    templateUrl: './footer.component.html',
    styleUrls: ['./footer.component.scss']
})

export class FooterComponent implements OnInit
{
    constructor() { }

    ngOnInit() { }

    getYear()
    {
      return new Date().getFullYear();
    }
}

<footer class="page-footer font-small special-color-dark pt-4 mt-5">
    <div class="container">
        <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item mx-2">
                <a target="_blank" class="btn-floating btn-fb mx-1" mdbWavesEffect href="https://www.facebook.com/AstroCorpESP/">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li class="list-inline-item mx-2">
                <a target="_blank" class="btn-floating btn-tw mx-1" mdbWavesEffect href="https://twitter.com/astro_corp">
                    <i class="fab fa-twitter"></i>
                </a>
            </li>
            <li class="list-inline-item mx-2">
                <a target="_blank" class="btn-floating btn-git mx-1" mdbWavesEffect href="https://github.com/AstroCorp">
                    <i class="fab fa-github"></i>
                </a>
            </li>
            <li class="list-inline-item mx-2">
              <a target="_blank" class="btn-floating btn-linkedin mx-1" mdbWavesEffect href="https://www.linkedin.com/in/alejandro-leal-bermúdez/">
                  <i class="fab fa-linkedin-in"></i>
              </a>
          </li>
            <li class="list-inline-item mx-2">
                <a target="_blank" class="btn-floating btn-twitch mx-1" mdbWavesEffect href="https://www.twitch.tv/astro_corp">
                    <i class="fab fa-twitch"></i>
                </a>
            </li>
            <li class="list-inline-item mx-2">
                <a target="_blank" class="btn-floating btn-yt mx-1" mdbWavesEffect href="https://www.youtube.com/c/AstroCorpESP">
                    <i class="fab fa-youtube"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="footer-copyright text-center py-3">© {{ getYear() }} Copyright Alejandro Leal Bermúdez. Todos los derechos reservados.</div>
</footer>

// src/components/Footer.vue
<template>
    <footer class="flex flex-wrap bg-starts py-4">
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>
        <div class="flex justify-center flex-row w-full">
            <div v-for="(link, index) in links" :key="index" class="rounded-full h-12 w-12 text-xl text-white flex items-center m-1" :style="{ 'background-color': link.color }">
                <font-awesome-icon class="flex-1" :icon="['fab', link.icon]" />
            </div>
        </div>
        <div class="w-full text-center title text-xl mt-4">© {{ getYear }} Copyright Alejandro Leal Bermúdez. Todos los derechos reservados.</div>
    </footer>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class Footer extends Vue
{
    private links: any = [
        {
            icon: 'facebook-f',
            color: '#3B5998',
            url: 'https://www.facebook.com/AstroCorpESP/',
        },
        {
            icon: 'twitter',
            color: '#55ACEE',
            url: 'https://twitter.com/astro_corp',
        },
        {
            icon: 'github',
            color: '#2B6CAD',
            url: 'https://github.com/AstroCorp',
        },
        {
            icon: 'linkedin-in',
            color: '#0F5091',
            url: 'https://www.linkedin.com/in/alejandro-leal-bermúdez/',
        },
        {
            icon: 'twitch',
            color: '#9147FF',
            url: 'https://www.twitch.tv/astro_corp',
        },
        {
            icon: 'youtube',
            color: '#DD4B39',
            url: 'https://www.youtube.com/c/AstroCorpESP',
        }
    ];

    public get getYear(): number {
        return new Date().getFullYear();
    }
}
</script>

<style scoped lang="scss">

</style>
